# Generated by Django 4.2.16 on 2024-11-24 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('eth_balance', models.DecimalField(decimal_places=0, default=0, max_digits=28)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('block_hash', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('Finalized', 'Finalized'), ('Attested', 'Attested'), ('Proposed', 'Proposed'), ('Pending', 'Pending'), ('Uncle', 'Uncle'), ('Orphaned', 'Orphaned'), ('Invalid', 'Invalid')], max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('epoch', models.PositiveIntegerField()),
                ('slot', models.PositiveIntegerField()),
                ('reward', models.DecimalField(decimal_places=0, max_digits=28)),
                ('difficulty', models.DecimalField(decimal_places=0, max_digits=28)),
                ('state_root', models.CharField(max_length=64, unique=True)),
                ('withdrawal_root', models.CharField(max_length=64)),
                ('height', models.BigIntegerField()),
                ('nonce', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_address', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('creator_address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='contract_creator_address', to='blockchain.address')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_hash', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='blockchain.block')),
                ('from_address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='from_address', to='blockchain.address')),
                ('to_address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='to_address', to='blockchain.address')),
            ],
        ),
        migrations.CreateModel(
            name='ContractData',
            fields=[
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='blockchain.contract')),
                ('source_code', models.TextField()),
                ('bytecode', models.TextField()),
                ('name', models.CharField(max_length=255, null=True)),
                ('version', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mempool',
            fields=[
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='blockchain.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='blockchain.contract')),
                ('symbol', models.CharField(max_length=255)),
                ('supply', models.DecimalField(decimal_places=0, max_digits=65)),
                ('decimals', models.PositiveSmallIntegerField()),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionData',
            fields=[
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='blockchain.transaction')),
                ('status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Pending', 'Pending'), ('Failed', 'Failed'), ('Canceled', 'Canceled'), ('Dropped', 'Dropped'), ('Replaced', 'Replaced')], max_length=10)),
                ('value', models.DecimalField(decimal_places=0, max_digits=28)),
                ('eth_price', models.FloatField()),
                ('gas_limit', models.BigIntegerField()),
                ('base_fee', models.DecimalField(decimal_places=0, max_digits=28)),
                ('max_fee', models.DecimalField(decimal_places=0, max_digits=28)),
                ('priority_fee', models.DecimalField(decimal_places=0, max_digits=28)),
                ('input_data', models.TextField(null=True)),
                ('timestamp', models.DateTimeField()),
                ('gas_used', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Validator',
            fields=[
                ('validator_id', models.AutoField(primary_key=True, serialize=False)),
                ('withdrawal_address', models.CharField(max_length=40)),
                ('eth_staked', models.DecimalField(decimal_places=0, max_digits=28)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Pending', 'Pending'), ('Exited', 'Exited')], max_length=10)),
                ('slashed', models.BooleanField(default=False)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='validator_address', to='blockchain.address')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='blockchain.transaction'),
        ),
        migrations.AddField(
            model_name='block',
            name='validator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='blockchain.validator'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['eth_balance'], name='idx_eth_balance'),
        ),
        migrations.AddIndex(
            model_name='validator',
            index=models.Index(fields=['status'], name='idx_status'),
        ),
        migrations.AddIndex(
            model_name='transactiondata',
            index=models.Index(fields=['timestamp'], name='idx_transaction_data_timestamp'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['symbol'], name='idx_token_symbol'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['type'], name='idx_token_type'),
        ),
        migrations.AddIndex(
            model_name='contractdata',
            index=models.Index(fields=['name'], name='idx_contract_data_name'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['status'], name='idx_block_status'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['timestamp'], name='idx_block_timestamp'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['epoch'], name='idx_block_epoch'),
        ),
    ]
